generator int simple_alu(int x, int y) {
  int opcode = ??(2);
  if (opcode == 0) {
    return x + y;
  } else if (opcode == 1) {
    return x * y;
  } else if (opcode == 2) {
    return x - y;
  } else {
    assert(opcode == 3);
    return x / y;
  }
}

harness void main(int x, int y, int z) {
  assume (y != 0);
  int result = simple_alu(x, y);
  int result2 = simple_alu(result, z);
  assert(x / y + z == result2);
}
