// Spec for Sketch
| StateAndPacket | program(| StateAndPacket | state_and_packet) {
  state_and_packet.pkt_1 = state_and_packet.pkt_0 + 1 + state_and_packet.pkt_1;
  state_and_packet.state_group_0_state_0 =
      state_and_packet.state_group_0_state_0 + 1;
  state_and_packet.state_group_1_state_0 =
      state_and_packet.state_group_0_state_0 +
      state_and_packet.state_group_1_state_0;
  state_and_packet.pkt_0 =
      state_and_packet.state_group_0_state_0 + state_and_packet.pkt_1;
  state_and_packet.pkt_2 = state_and_packet.state_group_0_state_0 +
                           state_and_packet.state_group_1_state_0;
  return state_and_packet;
}
