generator int Opt(int op1) {
  bit enable = ??(1);
  if (! enable) return 0;

  return op1;
}

generator int Mux2(int op1, int op2) {
  int choice = ??(1);
  if (choice == 0) return op1;
  else if (choice == 1) return op2;
}

generator int Mux3(int op1, int op2, int op3) {
  int choice = ??(2);
  if (choice == 0) return op1;
  else if (choice == 1) return op2;
  else if (choice == 2) return op3;
  else assert(false);
}
